43081j/eslint-plugin-wc

- src/rules/no-constructor-attributes.ts
- src/test/rules/no-constructor-attributes_test.ts
This introduces some global properties to the banned members list as they are reflected by default/globally.
For example, `this.id = 'foo'` will reflect to the `id` attribute (thus breaking the custom element rules and causing an exception).
> no-constructor-attributes: introduce global property/attr detection

- src/test/rules/attach-shadow-constructor_test.ts
- src/test/rules/guard-super-call_test.ts
- src/test/rules/no-constructor-attributes_test.ts
- src/test/rules/no-self-class_test.ts
- src/test/rules/no-typos_test.ts
- src/util.ts
This enables us to detect classes decorated with `@customElement`.
It should make the plugin a lot more usable until we also have support for detecting `define` calls.
> add support for `@customElement` decorator

- docs/rules/no-constructor-attributes.md
- src/rules/no-constructor-attributes.ts
- src/test/rules/no-constructor-attributes_test.ts
Fix #46
A custom element instance can be created programmatically with `document.createElement`. Which means the class constructor may be called **before** the element has access to the DOM. This is why we can't modify the element itself in the constructor, including its light dom.
Yet, a shadow DOM is created _"inside"_ the element and doesn't need to wait until this element is attached to another DOM to be available. Therefore, no error will occur when accessing the shadowRoot inside a custom element constructor.
Actually, this is even the recommended approach, as it will allow building the Web Component "content" ahead of time (which may lead to better performance), in a 100% controlled environment (which may avoid some bugs).
- The element must not gain any attributes or children, as …
> fix: false positive when accessing shadow dom in constructor

- README.md
- docs/rules/no-constructor-params.md
- src/rules/no-constructor-params.ts
- src/test/rules/no-constructor-params_test.ts
- src/util.ts
Fixes 43081j/eslint-plugin-lit#82
I've also updated the lit plugin readme to reference this plugin so people know best practice is to use both.
This disallows things like:
```ts
class Foo extends HTMLElement {
constructor(param1, param2) {
// ...
}
}
```
because things like `createElement` and DOM won't pass any parameters.
cc @justinfagnani @stramel
> rule: no-constructor-params

- src/rules/attach-shadow-constructor.ts
- src/rules/guard-super-call.ts
- src/rules/no-closed-shadow-root.ts
- src/rules/no-constructor-attributes.ts
- src/rules/no-constructor-params.ts
- src/rules/no-invalid-element-name.ts
- src/rules/no-self-class.ts
- src/rules/no-typos.ts
- src/test/util_test.ts
- src/util.ts
The returned functions on the tree traverser return the type that the key specifies. By setting the param as `ESTree.Node` we were making it more generic and then required a check that it would be the type that it passes in. 
I simplified the typing to what it should be and removed the redundant checks.
Also, utilized the optional chaining operator in the util file to simplify the conditions a bit
> Remove redundant checks

- README.md
- docs/rules/require-listener-teardown.md
- package-lock.json
- package.json
- src/rules/require-listener-teardown.ts
- src/test/rules/require-listener-teardown_test.ts
- src/test/util_test.ts
- src/util.ts
This requires that listeners added in `connectedCallback` are removed in `disconnectedCallback`.
Some shortcomings where we should improve in future:
* It will only detect those attached directly to `this` for now
* It will not yet determine that the correct reference was passed to both cases (i.e. `addEventListener('x', foo)` is considered cleaned up if we see `removeEventListener('x', bar)`)
* It will check all classes without considering base class (should be ok since nobody else uses a connectedCallback usually)
cc @stramel
> rule: require-listener-teardown

- package-lock.json
- src/configs/best-practice.ts
- src/index.ts
- src/rules/require-listener-teardown.ts
- src/test/rules/require-listener-teardown_test.ts
Some rules were missing from the index, which prevents those rules from being referenced by existing configs or being set by devs. This adds all existing rules to the index and adds the missing ones to the `best-practices` preset for completion.
--
This resolves https://github.com/43081j/eslint-plugin-wc/issues/68 and https://github.com/43081j/eslint-plugin-wc/issues/69
> Add missing rules to index exports

- docs/rules/no-constructor-params.md
They _may_ be constructed directly, they just usually aren't.
> Clarify docs on CE constructors

- src/rules/expose-class-on-global.ts
- src/test/rules/expose-class-on-global_test.ts
Part of #82 
This one enforces that you define your custom elements on the global object
> feat (expose-class-on-global): new rule

- src/index.ts
- src/rules/no-constructor.ts
- src/test/rules/no-constructor_test.ts
This rule allows you to disallow constructors in custom element classes.
It is really a personal preference rule rather than best practice.
Some users may wish to disallow it to avoid problems around reconnection to DOM, etc.
> feat (no-constructor): new rule

- .eslintrc.json
- src/index.ts
- src/rules/tag-name-matches-class.ts
- src/test/rules/tag-name-matches-class_test.ts
- src/util.ts
- src/util/text.ts
Enforces that the tag name in `define(...)` matches the class name
> feat (tag-name-matches-class): new rule

- src/index.ts
- src/rules/no-child-traversal-in-connectedcallback.ts
- src/test/rules/no-child-traversal-in-connectedcallback_test.ts
- src/util/dom.ts
same as the one for attribute changed callback, but for `connectedCallback`
basically disallows child traversals in there
> feat (no-child-traversal-in-connectedcallback): new rule

- src/index.ts
- src/rules/no-child-traversal-in-attributechangedcallback.ts
- src/rules/no-child-traversal-in-connectedcallback.ts
- src/test/rules/no-child-traversal-in-attributechangedcallback_test.ts
- src/test/rules/no-child-traversal-in-connectedcallback_test.ts
- src/util/dom.ts
basically disallows querySelector, childNodes, etc etc in `attributeChangedCallback` - but specifically on `this` and `this.shadowRoot`
> feat (no-child-traversal-in-attributechangedcallback): new rule

- src/rules/define-tag-after-class-definition.ts
- src/rules/no-invalid-element-name.ts
- src/test/rules/define-tag-after-class-definition_test.ts
- src/util.ts
Can do the docs later for each of these rules
This one catches classes which haven't been defined at all or were defined before their associated class
> feat (define-tag-after-class-definition): new rule

- package-lock.json
- src/index.ts
- src/rules/define-tag-after-class-definition.ts
- src/rules/guard-define-call.ts
- src/rules/no-invalid-element-name.ts
- src/test/rules/guard-define-call_test.ts
- src/test/rules/no-child-traversal-in-connectedcallback_test.ts
- src/util.ts
- src/util/customElements.ts
Works the same as guard-for-in but for `define()` calls of custom elements.
For example:
```ts
// invalid
customElements.define('x-foo', Foo);
// valid
if (!customElements.get('x-foo')) {
customElements.define('x-foo', Foo);
}
```
cc @keithamus
> feat (guard-define-call): new rule

- src/index.ts
- src/rules/define-tag-after-class-definition.ts
- src/rules/expose-class-on-global.ts
- src/rules/no-exports-with-element.ts
- src/test/rules/no-exports-with-element_test.ts
- src/util/ast.ts
Disallows exports alongside a custom element unless they're `Event` classes.
e.g.
```ts
// invalid
export class Foo extends HTMLElement {}
export const bar = 303;
// valid
export class Foo extends HTMLElement {}
// also valid
export class Foo extends HTMLElement {}
export class Bar extends Event {}
```
cc @keithamus
> feat (no-exports-with-element): new rule

- .github/workflows/main.yml
- src/index.ts
- src/rules/no-invalid-extends.ts
- src/test/rules/no-invalid-extends_test.ts
- tsconfig.json
Enforces that custom elements extend from a list of allowed classes.
By default, the only allowed class is `HTMLElement` unless you use the `extends` option when defining the element. In those cases, it must extend the known built-in class (e.g. HTMLDivElement).
For example:
```ts
// invalid
/** @customElement */
class Foo extends Bar {}
customElements.define('foo', Foo);
// valid
/** @customElement */
class Foo extends HTMLElement {}
customElements.define('foo', Foo);
// also valid
/** @customElement */
class Foo extends HTMLDivElement {}
customElements.define('foo', Foo, {extends: 'div'});
// also invalid
/** @customElement */
class Foo extends HTMLDivElement {}
customElements.define('foo', Foo);
```
cc @keithamus
> feat (no-invalid-extends): new rule

- src/index.ts
- src/rules/file-name-matches-element.ts
- src/test/rules/file-name-matches-element_test.ts
- src/test/util/text_test.ts
- src/util/text.ts
Enforces that the filename of a file containing a custom element matches its class name according to the configured conventions.
For example, the default is `['kebab', 'camel']` which means the following examples are true:
```ts
// valid filename: someElement.js
// invalid filename: some_element.js
class SomeElement extends HTMLElement {}
```
With `matchDirectory: true` set:
```ts
// valid filename: foo/bar/someElement.js
// valid filename: bar/someElement.js
// valid filename: fooBarSomeElement.js
// invalid filename: some_element.js
class FooBarSomeElement extends HTMLElement {}
```
cc @keithamus this was probably the most difficult one. its not a lot of logic but getting my head around the various nested pieces of logic took a while 😂 
but its the last one! 🎉
> feat (file-name-matches-element): new rule

- docs/rules/expose-class-on-global.md
This adds docs for `expose-class-on-global` which was recently added in #85.
Refs #82
> Add expose-class-on-global docs

- docs/rules/define-tag-after-class-definition.md
This adds docs for `define-tag-after-class-definition` which was recently added in #84 
Refs https://github.com/43081j/eslint-plugin-wc/issues/82
> Add define-tag-after-class-definition docs

- src/rules/expose-class-on-global.ts
- src/test/rules/expose-class-on-global_test.ts
This changes the rule to allow:
```ts
window.Foo = class Foo extends HTMLElement {};
```
Which will then still disallow:
```ts
window.Foo = class extends HTMLElement {};
```
cc @keithamus this seems to align it to your docs then. can you let me know if this is what behaviour you expected?
> fix (expose-class-on-global): allow named class expressions

- docs/rules/no-invalid-element-name.md
New options have been added:
- `onlyAlphanum`
- `disallowNamespaces` (which replaces `loose` but the default is flipped)
- `suffix` (an array of required suffixes)
- `prefix` (an array of required prefixes)
cc @keithamus
> chore (no-invalid-element-name): update readme with new options

- docs/rules/no-exports-with-element.md
Adds docs migrated from the custom elements plugin for the `no-exports-with-element` rule.
cc @keithamus
> docs (no-exports-with-element): add docs

- docs/rules/no-customized-built-in-elements.md
Adds documentation for `no-customized-built-in-elements` rule.
These are pretty much directly migrated from the custom elements plugin other than some formatting changes (consistency with other docs in the repo).
cc @keithamus
> docs (no-customized-built-in-elements): add docs

- docs/rules/no-method-prefixed-with-on.md
These are migrated from the custom elements plugin.
cc @keithamus
> docs (no-method-prefixed-with-on): add docs

- docs/rules/no-constructor.md
These are migrated from the custom elements plugin as-is.
cc @keithamus
> docs (no-constructor): add docs

- src/rules/no-invalid-extends.ts
- src/test/rules/no-invalid-extends_test.ts
We should respect `elementBaseClasses` as acceptable base classes for custom elements when running the logic in this rule.
If it isn't set, we can default to `HTMLElement` as being the only base class.
> fix (no-invalid-extends): respect elementBaseClasses

- .eslintrc.json
- .github/workflows/main.yml
- package-lock.json
- package.json
- src/util/tag-names.ts
Upgraded any dev dependencies which were on outdated versions.
This included adding the `search` tag the newer typescript DOM lib has introduced.
Also involved an eslint rule name change typescript-eslint introduced.
> chore: upgrade dev dependencies

- package-lock.json
- package.json
- src/configs/recommended.ts
- src/rules/no-invalid-extends.ts
- src/test/util_test.ts
- src/util.ts
Introducing the `invalid-extends` rule into the best practice config resulted in a larger breaking change than expected: LitElement repos fail to lint without introducing an `elementBaseClasses` setting.
Since a large chunk of our consumers are lit users, it makes sense to add it to the recommended config so it doesn't need configuring individually.
> feat: add LitElement to recommended config

- src/index.ts
Two rules were missing from the index:
- `define-tag-after-class-definition`
- `expose-class-on-global`
One rule was misnamed:
- `guard-define-call` (was `guard-define`)
Fixes #122
> fix: add missing rules to index

- src/test/rules/file-name-matches-element_test.ts
- src/util/text.ts
We forgot to implement `none` as a case type/transform in the file-name-matches-element rule. It is basically a pass-through transform, i.e. the name of the class should be exactly the name of the file.
Fixes #126
> fix(file-name-matches-element): respect 'none' case type

- README.md
- src/configs/best-practice.ts
- src/configs/legacy-best-practice.ts
- src/configs/legacy-recommended.ts
- src/configs/recommended.ts
- src/index.ts
- src/test/configs_test.ts
This adds support for ESLint's new flat config feature.
There are now 3 exported configs:
- `recommended` (legacy/eslintrc)
- `best-practice` (legacy/eslintrc)
- `flat/recommended` (flat)
- `flat/best-practice` (flat)
In future, we will drop the legacy ones and replace them with the flat configs in a breaking change.
Fixes #131
> feat: add eslint flat config support

- package.json
- src/rules/attach-shadow-constructor.ts
- src/rules/define-tag-after-class-definition.ts
- src/rules/expose-class-on-global.ts
- src/rules/file-name-matches-element.ts
- src/rules/guard-super-call.ts
- src/rules/max-elements-per-file.ts
- src/rules/no-child-traversal-in-attributechangedcallback.ts
- src/rules/no-child-traversal-in-connectedcallback.ts
- src/rules/no-constructor-attributes.ts
- src/rules/no-constructor-params.ts
- src/rules/no-constructor.ts
- src/rules/no-customized-built-in-elements.ts
- src/rules/no-exports-with-element.ts
- src/rules/no-invalid-extends.ts
- src/rules/no-method-prefixed-with-on.ts
- src/rules/no-self-class.ts
- src/rules/no-typos.ts
- src/rules/require-listener-teardown.ts
- src/util/ast.ts
The `context.getScope()` function, removed in ESLint v9, was used in `src/rules/no-child-traversal-in-connectedcallback.ts`, causing an error when the rule was executed in ESLint v9.
This PR migrates the relevant part to the new `context.sourceCode.getScope(node)` and migrates other deprecated APIs such as `getSourceCode()` to the new API added in ESLint v8.40.0.
> Fix compatibility issue with ESLint v9

- README.md
The config instructions for ESLint flat configuration didn't work for me. I received this error message:
```
Oops! Something went wrong! :(                                                                                                                                                                                                                                                      
ESLint: 9.12.0                                                                                                                                                                                                                                                                      
A config object has a "plugins" key defined as an array of strings. …
```
> Fix flat config instructions

- package-lock.json
- src/rules/guard-define-call.ts
I was running into some compatibility issues with ESLint 9 for the `guard-define-call` rule:
```
ESLint: 9.20.1
TypeError: context.getAncestors is not a function
Occurred while linting
Rule: "wc/guard-define-call"
```
Tested out the rule update: https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/#context.getancestors() and this looks to fix the issue.
> Update `guard-define-call` rule for eslint 9 compat

- src/index.ts
ESLint still expects it in some CLI situations.
> fix: export a default for now

- src/rules/require-listener-teardown.ts
- src/test/rules/require-listener-teardown_test.ts
We currently report listeners with a `signal` as not being torn down if
we don't later use `removeEventListener`.
Since there's too many cases to check, this change just blanket allows
all listeners to have no teardown which have a `signal`.
Fixes #148
> fix: ignore listeners with signals
